// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: data_point_insertion_request.proto

package dto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataPointInsertionItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to TimeSeriesReference:
	//
	//	*DataPointInsertionItem_Id
	//	*DataPointInsertionItem_ExternalId
	//	*DataPointInsertionItem_InstanceId
	TimeSeriesReference isDataPointInsertionItem_TimeSeriesReference `protobuf_oneof:"timeSeriesReference"`
	// Types that are valid to be assigned to DatapointType:
	//
	//	*DataPointInsertionItem_NumericDatapoints
	//	*DataPointInsertionItem_StringDatapoints
	DatapointType isDataPointInsertionItem_DatapointType `protobuf_oneof:"datapointType"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataPointInsertionItem) Reset() {
	*x = DataPointInsertionItem{}
	mi := &file_data_point_insertion_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataPointInsertionItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPointInsertionItem) ProtoMessage() {}

func (x *DataPointInsertionItem) ProtoReflect() protoreflect.Message {
	mi := &file_data_point_insertion_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataPointInsertionItem.ProtoReflect.Descriptor instead.
func (*DataPointInsertionItem) Descriptor() ([]byte, []int) {
	return file_data_point_insertion_request_proto_rawDescGZIP(), []int{0}
}

func (x *DataPointInsertionItem) GetTimeSeriesReference() isDataPointInsertionItem_TimeSeriesReference {
	if x != nil {
		return x.TimeSeriesReference
	}
	return nil
}

func (x *DataPointInsertionItem) GetId() int64 {
	if x != nil {
		if x, ok := x.TimeSeriesReference.(*DataPointInsertionItem_Id); ok {
			return x.Id
		}
	}
	return 0
}

func (x *DataPointInsertionItem) GetExternalId() string {
	if x != nil {
		if x, ok := x.TimeSeriesReference.(*DataPointInsertionItem_ExternalId); ok {
			return x.ExternalId
		}
	}
	return ""
}

func (x *DataPointInsertionItem) GetInstanceId() *InstanceId {
	if x != nil {
		if x, ok := x.TimeSeriesReference.(*DataPointInsertionItem_InstanceId); ok {
			return x.InstanceId
		}
	}
	return nil
}

func (x *DataPointInsertionItem) GetDatapointType() isDataPointInsertionItem_DatapointType {
	if x != nil {
		return x.DatapointType
	}
	return nil
}

func (x *DataPointInsertionItem) GetNumericDatapoints() *NumericDatapoints {
	if x != nil {
		if x, ok := x.DatapointType.(*DataPointInsertionItem_NumericDatapoints); ok {
			return x.NumericDatapoints
		}
	}
	return nil
}

func (x *DataPointInsertionItem) GetStringDatapoints() *StringDatapoints {
	if x != nil {
		if x, ok := x.DatapointType.(*DataPointInsertionItem_StringDatapoints); ok {
			return x.StringDatapoints
		}
	}
	return nil
}

type isDataPointInsertionItem_TimeSeriesReference interface {
	isDataPointInsertionItem_TimeSeriesReference()
}

type DataPointInsertionItem_Id struct {
	Id int64 `protobuf:"varint,1,opt,name=id,proto3,oneof"`
}

type DataPointInsertionItem_ExternalId struct {
	ExternalId string `protobuf:"bytes,2,opt,name=externalId,proto3,oneof"`
}

type DataPointInsertionItem_InstanceId struct {
	InstanceId *InstanceId `protobuf:"bytes,5,opt,name=instanceId,proto3,oneof"`
}

func (*DataPointInsertionItem_Id) isDataPointInsertionItem_TimeSeriesReference() {}

func (*DataPointInsertionItem_ExternalId) isDataPointInsertionItem_TimeSeriesReference() {}

func (*DataPointInsertionItem_InstanceId) isDataPointInsertionItem_TimeSeriesReference() {}

type isDataPointInsertionItem_DatapointType interface {
	isDataPointInsertionItem_DatapointType()
}

type DataPointInsertionItem_NumericDatapoints struct {
	NumericDatapoints *NumericDatapoints `protobuf:"bytes,3,opt,name=numericDatapoints,proto3,oneof"`
}

type DataPointInsertionItem_StringDatapoints struct {
	StringDatapoints *StringDatapoints `protobuf:"bytes,4,opt,name=stringDatapoints,proto3,oneof"`
}

func (*DataPointInsertionItem_NumericDatapoints) isDataPointInsertionItem_DatapointType() {}

func (*DataPointInsertionItem_StringDatapoints) isDataPointInsertionItem_DatapointType() {}

type DataPointInsertionRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Items         []*DataPointInsertionItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataPointInsertionRequest) Reset() {
	*x = DataPointInsertionRequest{}
	mi := &file_data_point_insertion_request_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataPointInsertionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPointInsertionRequest) ProtoMessage() {}

func (x *DataPointInsertionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_point_insertion_request_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataPointInsertionRequest.ProtoReflect.Descriptor instead.
func (*DataPointInsertionRequest) Descriptor() ([]byte, []int) {
	return file_data_point_insertion_request_proto_rawDescGZIP(), []int{1}
}

func (x *DataPointInsertionRequest) GetItems() []*DataPointInsertionItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_data_point_insertion_request_proto protoreflect.FileDescriptor

const file_data_point_insertion_request_proto_rawDesc = "" +
	"\n" +
	"\"data_point_insertion_request.proto\x12\x1fcom.cognite.v1.timeseries.proto\x1a\x11data_points.proto\"\x88\x03\n" +
	"\x16DataPointInsertionItem\x12\x10\n" +
	"\x02id\x18\x01 \x01(\x03H\x00R\x02id\x12 \n" +
	"\n" +
	"externalId\x18\x02 \x01(\tH\x00R\n" +
	"externalId\x12M\n" +
	"\n" +
	"instanceId\x18\x05 \x01(\v2+.com.cognite.v1.timeseries.proto.InstanceIdH\x00R\n" +
	"instanceId\x12b\n" +
	"\x11numericDatapoints\x18\x03 \x01(\v22.com.cognite.v1.timeseries.proto.NumericDatapointsH\x01R\x11numericDatapoints\x12_\n" +
	"\x10stringDatapoints\x18\x04 \x01(\v21.com.cognite.v1.timeseries.proto.StringDatapointsH\x01R\x10stringDatapointsB\x15\n" +
	"\x13timeSeriesReferenceB\x0f\n" +
	"\rdatapointType\"j\n" +
	"\x19DataPointInsertionRequest\x12M\n" +
	"\x05items\x18\x01 \x03(\v27.com.cognite.v1.timeseries.proto.DataPointInsertionItemR\x05itemsB5P\x01Z1github.com/evertoncolling/poc-requests-go/pkg/dtob\x06proto3"

var (
	file_data_point_insertion_request_proto_rawDescOnce sync.Once
	file_data_point_insertion_request_proto_rawDescData []byte
)

func file_data_point_insertion_request_proto_rawDescGZIP() []byte {
	file_data_point_insertion_request_proto_rawDescOnce.Do(func() {
		file_data_point_insertion_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_data_point_insertion_request_proto_rawDesc), len(file_data_point_insertion_request_proto_rawDesc)))
	})
	return file_data_point_insertion_request_proto_rawDescData
}

var file_data_point_insertion_request_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_data_point_insertion_request_proto_goTypes = []any{
	(*DataPointInsertionItem)(nil),    // 0: com.cognite.v1.timeseries.proto.DataPointInsertionItem
	(*DataPointInsertionRequest)(nil), // 1: com.cognite.v1.timeseries.proto.DataPointInsertionRequest
	(*InstanceId)(nil),                // 2: com.cognite.v1.timeseries.proto.InstanceId
	(*NumericDatapoints)(nil),         // 3: com.cognite.v1.timeseries.proto.NumericDatapoints
	(*StringDatapoints)(nil),          // 4: com.cognite.v1.timeseries.proto.StringDatapoints
}
var file_data_point_insertion_request_proto_depIdxs = []int32{
	2, // 0: com.cognite.v1.timeseries.proto.DataPointInsertionItem.instanceId:type_name -> com.cognite.v1.timeseries.proto.InstanceId
	3, // 1: com.cognite.v1.timeseries.proto.DataPointInsertionItem.numericDatapoints:type_name -> com.cognite.v1.timeseries.proto.NumericDatapoints
	4, // 2: com.cognite.v1.timeseries.proto.DataPointInsertionItem.stringDatapoints:type_name -> com.cognite.v1.timeseries.proto.StringDatapoints
	0, // 3: com.cognite.v1.timeseries.proto.DataPointInsertionRequest.items:type_name -> com.cognite.v1.timeseries.proto.DataPointInsertionItem
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_data_point_insertion_request_proto_init() }
func file_data_point_insertion_request_proto_init() {
	if File_data_point_insertion_request_proto != nil {
		return
	}
	file_data_points_proto_init()
	file_data_point_insertion_request_proto_msgTypes[0].OneofWrappers = []any{
		(*DataPointInsertionItem_Id)(nil),
		(*DataPointInsertionItem_ExternalId)(nil),
		(*DataPointInsertionItem_InstanceId)(nil),
		(*DataPointInsertionItem_NumericDatapoints)(nil),
		(*DataPointInsertionItem_StringDatapoints)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_data_point_insertion_request_proto_rawDesc), len(file_data_point_insertion_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_data_point_insertion_request_proto_goTypes,
		DependencyIndexes: file_data_point_insertion_request_proto_depIdxs,
		MessageInfos:      file_data_point_insertion_request_proto_msgTypes,
	}.Build()
	File_data_point_insertion_request_proto = out.File
	file_data_point_insertion_request_proto_goTypes = nil
	file_data_point_insertion_request_proto_depIdxs = nil
}
