// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: data_point_list_response.proto

package dto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataPointListItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ExternalId     string                 `protobuf:"bytes,2,opt,name=externalId,proto3" json:"externalId,omitempty"`
	InstanceId     *InstanceId            `protobuf:"bytes,11,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	IsString       bool                   `protobuf:"varint,6,opt,name=isString,proto3" json:"isString,omitempty"`
	IsStep         bool                   `protobuf:"varint,7,opt,name=isStep,proto3" json:"isStep,omitempty"`
	Unit           string                 `protobuf:"bytes,8,opt,name=unit,proto3" json:"unit,omitempty"`
	NextCursor     string                 `protobuf:"bytes,9,opt,name=nextCursor,proto3" json:"nextCursor,omitempty"`
	UnitExternalId string                 `protobuf:"bytes,10,opt,name=unitExternalId,proto3" json:"unitExternalId,omitempty"`
	// Types that are valid to be assigned to DatapointType:
	//
	//	*DataPointListItem_NumericDatapoints
	//	*DataPointListItem_StringDatapoints
	//	*DataPointListItem_AggregateDatapoints
	DatapointType isDataPointListItem_DatapointType `protobuf_oneof:"datapointType"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataPointListItem) Reset() {
	*x = DataPointListItem{}
	mi := &file_data_point_list_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataPointListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPointListItem) ProtoMessage() {}

func (x *DataPointListItem) ProtoReflect() protoreflect.Message {
	mi := &file_data_point_list_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataPointListItem.ProtoReflect.Descriptor instead.
func (*DataPointListItem) Descriptor() ([]byte, []int) {
	return file_data_point_list_response_proto_rawDescGZIP(), []int{0}
}

func (x *DataPointListItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DataPointListItem) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *DataPointListItem) GetInstanceId() *InstanceId {
	if x != nil {
		return x.InstanceId
	}
	return nil
}

func (x *DataPointListItem) GetIsString() bool {
	if x != nil {
		return x.IsString
	}
	return false
}

func (x *DataPointListItem) GetIsStep() bool {
	if x != nil {
		return x.IsStep
	}
	return false
}

func (x *DataPointListItem) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *DataPointListItem) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *DataPointListItem) GetUnitExternalId() string {
	if x != nil {
		return x.UnitExternalId
	}
	return ""
}

func (x *DataPointListItem) GetDatapointType() isDataPointListItem_DatapointType {
	if x != nil {
		return x.DatapointType
	}
	return nil
}

func (x *DataPointListItem) GetNumericDatapoints() *NumericDatapoints {
	if x != nil {
		if x, ok := x.DatapointType.(*DataPointListItem_NumericDatapoints); ok {
			return x.NumericDatapoints
		}
	}
	return nil
}

func (x *DataPointListItem) GetStringDatapoints() *StringDatapoints {
	if x != nil {
		if x, ok := x.DatapointType.(*DataPointListItem_StringDatapoints); ok {
			return x.StringDatapoints
		}
	}
	return nil
}

func (x *DataPointListItem) GetAggregateDatapoints() *AggregateDatapoints {
	if x != nil {
		if x, ok := x.DatapointType.(*DataPointListItem_AggregateDatapoints); ok {
			return x.AggregateDatapoints
		}
	}
	return nil
}

type isDataPointListItem_DatapointType interface {
	isDataPointListItem_DatapointType()
}

type DataPointListItem_NumericDatapoints struct {
	NumericDatapoints *NumericDatapoints `protobuf:"bytes,3,opt,name=numericDatapoints,proto3,oneof"`
}

type DataPointListItem_StringDatapoints struct {
	StringDatapoints *StringDatapoints `protobuf:"bytes,4,opt,name=stringDatapoints,proto3,oneof"`
}

type DataPointListItem_AggregateDatapoints struct {
	AggregateDatapoints *AggregateDatapoints `protobuf:"bytes,5,opt,name=aggregateDatapoints,proto3,oneof"`
}

func (*DataPointListItem_NumericDatapoints) isDataPointListItem_DatapointType() {}

func (*DataPointListItem_StringDatapoints) isDataPointListItem_DatapointType() {}

func (*DataPointListItem_AggregateDatapoints) isDataPointListItem_DatapointType() {}

type DataPointListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*DataPointListItem   `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataPointListResponse) Reset() {
	*x = DataPointListResponse{}
	mi := &file_data_point_list_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataPointListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPointListResponse) ProtoMessage() {}

func (x *DataPointListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_point_list_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataPointListResponse.ProtoReflect.Descriptor instead.
func (*DataPointListResponse) Descriptor() ([]byte, []int) {
	return file_data_point_list_response_proto_rawDescGZIP(), []int{1}
}

func (x *DataPointListResponse) GetItems() []*DataPointListItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_data_point_list_response_proto protoreflect.FileDescriptor

const file_data_point_list_response_proto_rawDesc = "" +
	"\n" +
	"\x1edata_point_list_response.proto\x12\x1fcom.cognite.v1.timeseries.proto\x1a\x11data_points.proto\"\xe0\x04\n" +
	"\x11DataPointListItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1e\n" +
	"\n" +
	"externalId\x18\x02 \x01(\tR\n" +
	"externalId\x12K\n" +
	"\n" +
	"instanceId\x18\v \x01(\v2+.com.cognite.v1.timeseries.proto.InstanceIdR\n" +
	"instanceId\x12\x1a\n" +
	"\bisString\x18\x06 \x01(\bR\bisString\x12\x16\n" +
	"\x06isStep\x18\a \x01(\bR\x06isStep\x12\x12\n" +
	"\x04unit\x18\b \x01(\tR\x04unit\x12\x1e\n" +
	"\n" +
	"nextCursor\x18\t \x01(\tR\n" +
	"nextCursor\x12&\n" +
	"\x0eunitExternalId\x18\n" +
	" \x01(\tR\x0eunitExternalId\x12b\n" +
	"\x11numericDatapoints\x18\x03 \x01(\v22.com.cognite.v1.timeseries.proto.NumericDatapointsH\x00R\x11numericDatapoints\x12_\n" +
	"\x10stringDatapoints\x18\x04 \x01(\v21.com.cognite.v1.timeseries.proto.StringDatapointsH\x00R\x10stringDatapoints\x12h\n" +
	"\x13aggregateDatapoints\x18\x05 \x01(\v24.com.cognite.v1.timeseries.proto.AggregateDatapointsH\x00R\x13aggregateDatapointsB\x0f\n" +
	"\rdatapointType\"a\n" +
	"\x15DataPointListResponse\x12H\n" +
	"\x05items\x18\x01 \x03(\v22.com.cognite.v1.timeseries.proto.DataPointListItemR\x05itemsB5P\x01Z1github.com/evertoncolling/poc-requests-go/pkg/dtob\x06proto3"

var (
	file_data_point_list_response_proto_rawDescOnce sync.Once
	file_data_point_list_response_proto_rawDescData []byte
)

func file_data_point_list_response_proto_rawDescGZIP() []byte {
	file_data_point_list_response_proto_rawDescOnce.Do(func() {
		file_data_point_list_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_data_point_list_response_proto_rawDesc), len(file_data_point_list_response_proto_rawDesc)))
	})
	return file_data_point_list_response_proto_rawDescData
}

var file_data_point_list_response_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_data_point_list_response_proto_goTypes = []any{
	(*DataPointListItem)(nil),     // 0: com.cognite.v1.timeseries.proto.DataPointListItem
	(*DataPointListResponse)(nil), // 1: com.cognite.v1.timeseries.proto.DataPointListResponse
	(*InstanceId)(nil),            // 2: com.cognite.v1.timeseries.proto.InstanceId
	(*NumericDatapoints)(nil),     // 3: com.cognite.v1.timeseries.proto.NumericDatapoints
	(*StringDatapoints)(nil),      // 4: com.cognite.v1.timeseries.proto.StringDatapoints
	(*AggregateDatapoints)(nil),   // 5: com.cognite.v1.timeseries.proto.AggregateDatapoints
}
var file_data_point_list_response_proto_depIdxs = []int32{
	2, // 0: com.cognite.v1.timeseries.proto.DataPointListItem.instanceId:type_name -> com.cognite.v1.timeseries.proto.InstanceId
	3, // 1: com.cognite.v1.timeseries.proto.DataPointListItem.numericDatapoints:type_name -> com.cognite.v1.timeseries.proto.NumericDatapoints
	4, // 2: com.cognite.v1.timeseries.proto.DataPointListItem.stringDatapoints:type_name -> com.cognite.v1.timeseries.proto.StringDatapoints
	5, // 3: com.cognite.v1.timeseries.proto.DataPointListItem.aggregateDatapoints:type_name -> com.cognite.v1.timeseries.proto.AggregateDatapoints
	0, // 4: com.cognite.v1.timeseries.proto.DataPointListResponse.items:type_name -> com.cognite.v1.timeseries.proto.DataPointListItem
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_data_point_list_response_proto_init() }
func file_data_point_list_response_proto_init() {
	if File_data_point_list_response_proto != nil {
		return
	}
	file_data_points_proto_init()
	file_data_point_list_response_proto_msgTypes[0].OneofWrappers = []any{
		(*DataPointListItem_NumericDatapoints)(nil),
		(*DataPointListItem_StringDatapoints)(nil),
		(*DataPointListItem_AggregateDatapoints)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_data_point_list_response_proto_rawDesc), len(file_data_point_list_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_data_point_list_response_proto_goTypes,
		DependencyIndexes: file_data_point_list_response_proto_depIdxs,
		MessageInfos:      file_data_point_list_response_proto_msgTypes,
	}.Build()
	File_data_point_list_response_proto = out.File
	file_data_point_list_response_proto_goTypes = nil
	file_data_point_list_response_proto_depIdxs = nil
}
