// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.0
// source: data_points.proto

package dto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NumericDatapoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp int64   `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Value     float64 `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *NumericDatapoint) Reset() {
	*x = NumericDatapoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_points_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NumericDatapoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumericDatapoint) ProtoMessage() {}

func (x *NumericDatapoint) ProtoReflect() protoreflect.Message {
	mi := &file_data_points_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumericDatapoint.ProtoReflect.Descriptor instead.
func (*NumericDatapoint) Descriptor() ([]byte, []int) {
	return file_data_points_proto_rawDescGZIP(), []int{0}
}

func (x *NumericDatapoint) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *NumericDatapoint) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type NumericDatapoints struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Datapoints []*NumericDatapoint `protobuf:"bytes,1,rep,name=datapoints,proto3" json:"datapoints,omitempty"`
}

func (x *NumericDatapoints) Reset() {
	*x = NumericDatapoints{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_points_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NumericDatapoints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumericDatapoints) ProtoMessage() {}

func (x *NumericDatapoints) ProtoReflect() protoreflect.Message {
	mi := &file_data_points_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumericDatapoints.ProtoReflect.Descriptor instead.
func (*NumericDatapoints) Descriptor() ([]byte, []int) {
	return file_data_points_proto_rawDescGZIP(), []int{1}
}

func (x *NumericDatapoints) GetDatapoints() []*NumericDatapoint {
	if x != nil {
		return x.Datapoints
	}
	return nil
}

type StringDatapoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp int64  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Value     string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *StringDatapoint) Reset() {
	*x = StringDatapoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_points_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringDatapoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringDatapoint) ProtoMessage() {}

func (x *StringDatapoint) ProtoReflect() protoreflect.Message {
	mi := &file_data_points_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringDatapoint.ProtoReflect.Descriptor instead.
func (*StringDatapoint) Descriptor() ([]byte, []int) {
	return file_data_points_proto_rawDescGZIP(), []int{2}
}

func (x *StringDatapoint) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *StringDatapoint) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type StringDatapoints struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Datapoints []*StringDatapoint `protobuf:"bytes,1,rep,name=datapoints,proto3" json:"datapoints,omitempty"`
}

func (x *StringDatapoints) Reset() {
	*x = StringDatapoints{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_points_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringDatapoints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringDatapoints) ProtoMessage() {}

func (x *StringDatapoints) ProtoReflect() protoreflect.Message {
	mi := &file_data_points_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringDatapoints.ProtoReflect.Descriptor instead.
func (*StringDatapoints) Descriptor() ([]byte, []int) {
	return file_data_points_proto_rawDescGZIP(), []int{3}
}

func (x *StringDatapoints) GetDatapoints() []*StringDatapoint {
	if x != nil {
		return x.Datapoints
	}
	return nil
}

type AggregateDatapoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp          int64   `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Average            float64 `protobuf:"fixed64,2,opt,name=average,proto3" json:"average,omitempty"`
	Max                float64 `protobuf:"fixed64,3,opt,name=max,proto3" json:"max,omitempty"`
	Min                float64 `protobuf:"fixed64,4,opt,name=min,proto3" json:"min,omitempty"`
	Count              float64 `protobuf:"fixed64,5,opt,name=count,proto3" json:"count,omitempty"`
	Sum                float64 `protobuf:"fixed64,6,opt,name=sum,proto3" json:"sum,omitempty"`
	Interpolation      float64 `protobuf:"fixed64,7,opt,name=interpolation,proto3" json:"interpolation,omitempty"`
	StepInterpolation  float64 `protobuf:"fixed64,8,opt,name=stepInterpolation,proto3" json:"stepInterpolation,omitempty"`
	ContinuousVariance float64 `protobuf:"fixed64,9,opt,name=continuousVariance,proto3" json:"continuousVariance,omitempty"`
	DiscreteVariance   float64 `protobuf:"fixed64,10,opt,name=discreteVariance,proto3" json:"discreteVariance,omitempty"`
	TotalVariation     float64 `protobuf:"fixed64,11,opt,name=totalVariation,proto3" json:"totalVariation,omitempty"`
}

func (x *AggregateDatapoint) Reset() {
	*x = AggregateDatapoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_points_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AggregateDatapoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregateDatapoint) ProtoMessage() {}

func (x *AggregateDatapoint) ProtoReflect() protoreflect.Message {
	mi := &file_data_points_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregateDatapoint.ProtoReflect.Descriptor instead.
func (*AggregateDatapoint) Descriptor() ([]byte, []int) {
	return file_data_points_proto_rawDescGZIP(), []int{4}
}

func (x *AggregateDatapoint) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AggregateDatapoint) GetAverage() float64 {
	if x != nil {
		return x.Average
	}
	return 0
}

func (x *AggregateDatapoint) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *AggregateDatapoint) GetMin() float64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *AggregateDatapoint) GetCount() float64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *AggregateDatapoint) GetSum() float64 {
	if x != nil {
		return x.Sum
	}
	return 0
}

func (x *AggregateDatapoint) GetInterpolation() float64 {
	if x != nil {
		return x.Interpolation
	}
	return 0
}

func (x *AggregateDatapoint) GetStepInterpolation() float64 {
	if x != nil {
		return x.StepInterpolation
	}
	return 0
}

func (x *AggregateDatapoint) GetContinuousVariance() float64 {
	if x != nil {
		return x.ContinuousVariance
	}
	return 0
}

func (x *AggregateDatapoint) GetDiscreteVariance() float64 {
	if x != nil {
		return x.DiscreteVariance
	}
	return 0
}

func (x *AggregateDatapoint) GetTotalVariation() float64 {
	if x != nil {
		return x.TotalVariation
	}
	return 0
}

type AggregateDatapoints struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Datapoints []*AggregateDatapoint `protobuf:"bytes,1,rep,name=datapoints,proto3" json:"datapoints,omitempty"`
}

func (x *AggregateDatapoints) Reset() {
	*x = AggregateDatapoints{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_points_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AggregateDatapoints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregateDatapoints) ProtoMessage() {}

func (x *AggregateDatapoints) ProtoReflect() protoreflect.Message {
	mi := &file_data_points_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregateDatapoints.ProtoReflect.Descriptor instead.
func (*AggregateDatapoints) Descriptor() ([]byte, []int) {
	return file_data_points_proto_rawDescGZIP(), []int{5}
}

func (x *AggregateDatapoints) GetDatapoints() []*AggregateDatapoint {
	if x != nil {
		return x.Datapoints
	}
	return nil
}

var File_data_points_proto protoreflect.FileDescriptor

var file_data_points_proto_rawDesc = []byte{
	0x0a, 0x11, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x1f, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x6f, 0x67, 0x6e, 0x69, 0x74, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x69, 0x65, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x46, 0x0a, 0x10, 0x4e, 0x75, 0x6d, 0x65, 0x72, 0x69, 0x63, 0x44,
	0x61, 0x74, 0x61, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x66, 0x0a, 0x11,
	0x4e, 0x75, 0x6d, 0x65, 0x72, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x73, 0x12, 0x51, 0x0a, 0x0a, 0x64, 0x61, 0x74, 0x61, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x6f, 0x67, 0x6e,
	0x69, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x69, 0x65,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x75, 0x6d, 0x65, 0x72, 0x69, 0x63, 0x44,
	0x61, 0x74, 0x61, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x0a, 0x64, 0x61, 0x74, 0x61, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x73, 0x22, 0x45, 0x0a, 0x0f, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x44, 0x61,
	0x74, 0x61, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x64, 0x0a, 0x10, 0x53,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x44, 0x61, 0x74, 0x61, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12,
	0x50, 0x0a, 0x0a, 0x64, 0x61, 0x74, 0x61, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x6f, 0x67, 0x6e, 0x69, 0x74,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x69, 0x65, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x44, 0x61, 0x74, 0x61,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x0a, 0x64, 0x61, 0x74, 0x61, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x73, 0x22, 0xf0, 0x02, 0x0a, 0x12, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x76, 0x65, 0x72, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x61, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6d,
	0x61, 0x78, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x03, 0x6d, 0x69, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x75,
	0x6d, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x73, 0x75, 0x6d, 0x12, 0x24, 0x0a, 0x0d,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x0d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x6f, 0x6c, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x2c, 0x0a, 0x11, 0x73, 0x74, 0x65, 0x70, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x70,
	0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x01, 0x52, 0x11, 0x73,
	0x74, 0x65, 0x70, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x2e, 0x0a, 0x12, 0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x6f, 0x75, 0x73, 0x56, 0x61,
	0x72, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x01, 0x52, 0x12, 0x63, 0x6f,
	0x6e, 0x74, 0x69, 0x6e, 0x75, 0x6f, 0x75, 0x73, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x63, 0x65,
	0x12, 0x2a, 0x0a, 0x10, 0x64, 0x69, 0x73, 0x63, 0x72, 0x65, 0x74, 0x65, 0x56, 0x61, 0x72, 0x69,
	0x61, 0x6e, 0x63, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x01, 0x52, 0x10, 0x64, 0x69, 0x73, 0x63,
	0x72, 0x65, 0x74, 0x65, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x26, 0x0a, 0x0e,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x56, 0x61, 0x72, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x0e, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x56, 0x61, 0x72, 0x69, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x6a, 0x0a, 0x13, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x53, 0x0a, 0x0a, 0x64,
	0x61, 0x74, 0x61, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x33, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x6f, 0x67, 0x6e, 0x69, 0x74, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x69, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x52, 0x0a, 0x64, 0x61, 0x74, 0x61, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73,
	0x42, 0x23, 0x50, 0x01, 0x5a, 0x1f, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x6f, 0x67, 0x6e, 0x69, 0x74,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x69, 0x65, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_data_points_proto_rawDescOnce sync.Once
	file_data_points_proto_rawDescData = file_data_points_proto_rawDesc
)

func file_data_points_proto_rawDescGZIP() []byte {
	file_data_points_proto_rawDescOnce.Do(func() {
		file_data_points_proto_rawDescData = protoimpl.X.CompressGZIP(file_data_points_proto_rawDescData)
	})
	return file_data_points_proto_rawDescData
}

var file_data_points_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_data_points_proto_goTypes = []interface{}{
	(*NumericDatapoint)(nil),    // 0: com.cognite.v1.timeseries.proto.NumericDatapoint
	(*NumericDatapoints)(nil),   // 1: com.cognite.v1.timeseries.proto.NumericDatapoints
	(*StringDatapoint)(nil),     // 2: com.cognite.v1.timeseries.proto.StringDatapoint
	(*StringDatapoints)(nil),    // 3: com.cognite.v1.timeseries.proto.StringDatapoints
	(*AggregateDatapoint)(nil),  // 4: com.cognite.v1.timeseries.proto.AggregateDatapoint
	(*AggregateDatapoints)(nil), // 5: com.cognite.v1.timeseries.proto.AggregateDatapoints
}
var file_data_points_proto_depIdxs = []int32{
	0, // 0: com.cognite.v1.timeseries.proto.NumericDatapoints.datapoints:type_name -> com.cognite.v1.timeseries.proto.NumericDatapoint
	2, // 1: com.cognite.v1.timeseries.proto.StringDatapoints.datapoints:type_name -> com.cognite.v1.timeseries.proto.StringDatapoint
	4, // 2: com.cognite.v1.timeseries.proto.AggregateDatapoints.datapoints:type_name -> com.cognite.v1.timeseries.proto.AggregateDatapoint
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_data_points_proto_init() }
func file_data_points_proto_init() {
	if File_data_points_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_data_points_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NumericDatapoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_points_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NumericDatapoints); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_points_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StringDatapoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_points_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StringDatapoints); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_points_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AggregateDatapoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_points_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AggregateDatapoints); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_data_points_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_data_points_proto_goTypes,
		DependencyIndexes: file_data_points_proto_depIdxs,
		MessageInfos:      file_data_points_proto_msgTypes,
	}.Build()
	File_data_points_proto = out.File
	file_data_points_proto_rawDesc = nil
	file_data_points_proto_goTypes = nil
	file_data_points_proto_depIdxs = nil
}
