// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: data_points.proto

package dto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_data_points_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_data_points_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_data_points_proto_rawDescGZIP(), []int{0}
}

func (x *Status) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Status) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type NumericDatapoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	Status        *Status                `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	NullValue     bool                   `protobuf:"varint,4,opt,name=nullValue,proto3" json:"nullValue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NumericDatapoint) Reset() {
	*x = NumericDatapoint{}
	mi := &file_data_points_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumericDatapoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumericDatapoint) ProtoMessage() {}

func (x *NumericDatapoint) ProtoReflect() protoreflect.Message {
	mi := &file_data_points_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumericDatapoint.ProtoReflect.Descriptor instead.
func (*NumericDatapoint) Descriptor() ([]byte, []int) {
	return file_data_points_proto_rawDescGZIP(), []int{1}
}

func (x *NumericDatapoint) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *NumericDatapoint) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *NumericDatapoint) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *NumericDatapoint) GetNullValue() bool {
	if x != nil {
		return x.NullValue
	}
	return false
}

type NumericDatapoints struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Datapoints    []*NumericDatapoint    `protobuf:"bytes,1,rep,name=datapoints,proto3" json:"datapoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NumericDatapoints) Reset() {
	*x = NumericDatapoints{}
	mi := &file_data_points_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumericDatapoints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumericDatapoints) ProtoMessage() {}

func (x *NumericDatapoints) ProtoReflect() protoreflect.Message {
	mi := &file_data_points_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumericDatapoints.ProtoReflect.Descriptor instead.
func (*NumericDatapoints) Descriptor() ([]byte, []int) {
	return file_data_points_proto_rawDescGZIP(), []int{2}
}

func (x *NumericDatapoints) GetDatapoints() []*NumericDatapoint {
	if x != nil {
		return x.Datapoints
	}
	return nil
}

type StringDatapoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Status        *Status                `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	NullValue     bool                   `protobuf:"varint,4,opt,name=nullValue,proto3" json:"nullValue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringDatapoint) Reset() {
	*x = StringDatapoint{}
	mi := &file_data_points_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringDatapoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringDatapoint) ProtoMessage() {}

func (x *StringDatapoint) ProtoReflect() protoreflect.Message {
	mi := &file_data_points_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringDatapoint.ProtoReflect.Descriptor instead.
func (*StringDatapoint) Descriptor() ([]byte, []int) {
	return file_data_points_proto_rawDescGZIP(), []int{3}
}

func (x *StringDatapoint) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *StringDatapoint) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *StringDatapoint) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *StringDatapoint) GetNullValue() bool {
	if x != nil {
		return x.NullValue
	}
	return false
}

type StringDatapoints struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Datapoints    []*StringDatapoint     `protobuf:"bytes,1,rep,name=datapoints,proto3" json:"datapoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringDatapoints) Reset() {
	*x = StringDatapoints{}
	mi := &file_data_points_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringDatapoints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringDatapoints) ProtoMessage() {}

func (x *StringDatapoints) ProtoReflect() protoreflect.Message {
	mi := &file_data_points_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringDatapoints.ProtoReflect.Descriptor instead.
func (*StringDatapoints) Descriptor() ([]byte, []int) {
	return file_data_points_proto_rawDescGZIP(), []int{4}
}

func (x *StringDatapoints) GetDatapoints() []*StringDatapoint {
	if x != nil {
		return x.Datapoints
	}
	return nil
}

type AggregateDatapoint struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Timestamp          int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Average            float64                `protobuf:"fixed64,2,opt,name=average,proto3" json:"average,omitempty"`
	Max                float64                `protobuf:"fixed64,3,opt,name=max,proto3" json:"max,omitempty"`
	Min                float64                `protobuf:"fixed64,4,opt,name=min,proto3" json:"min,omitempty"`
	Count              float64                `protobuf:"fixed64,5,opt,name=count,proto3" json:"count,omitempty"`
	Sum                float64                `protobuf:"fixed64,6,opt,name=sum,proto3" json:"sum,omitempty"`
	Interpolation      float64                `protobuf:"fixed64,7,opt,name=interpolation,proto3" json:"interpolation,omitempty"`
	StepInterpolation  float64                `protobuf:"fixed64,8,opt,name=stepInterpolation,proto3" json:"stepInterpolation,omitempty"`
	ContinuousVariance float64                `protobuf:"fixed64,9,opt,name=continuousVariance,proto3" json:"continuousVariance,omitempty"`
	DiscreteVariance   float64                `protobuf:"fixed64,10,opt,name=discreteVariance,proto3" json:"discreteVariance,omitempty"`
	TotalVariation     float64                `protobuf:"fixed64,11,opt,name=totalVariation,proto3" json:"totalVariation,omitempty"`
	CountGood          float64                `protobuf:"fixed64,12,opt,name=countGood,proto3" json:"countGood,omitempty"`
	CountUncertain     float64                `protobuf:"fixed64,13,opt,name=countUncertain,proto3" json:"countUncertain,omitempty"`
	CountBad           float64                `protobuf:"fixed64,14,opt,name=countBad,proto3" json:"countBad,omitempty"`
	DurationGood       float64                `protobuf:"fixed64,15,opt,name=durationGood,proto3" json:"durationGood,omitempty"`
	DurationUncertain  float64                `protobuf:"fixed64,16,opt,name=durationUncertain,proto3" json:"durationUncertain,omitempty"`
	DurationBad        float64                `protobuf:"fixed64,17,opt,name=durationBad,proto3" json:"durationBad,omitempty"`
	MaxDatapoint       *NumericDatapoint      `protobuf:"bytes,18,opt,name=maxDatapoint,proto3" json:"maxDatapoint,omitempty"`
	MinDatapoint       *NumericDatapoint      `protobuf:"bytes,19,opt,name=minDatapoint,proto3" json:"minDatapoint,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AggregateDatapoint) Reset() {
	*x = AggregateDatapoint{}
	mi := &file_data_points_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregateDatapoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregateDatapoint) ProtoMessage() {}

func (x *AggregateDatapoint) ProtoReflect() protoreflect.Message {
	mi := &file_data_points_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregateDatapoint.ProtoReflect.Descriptor instead.
func (*AggregateDatapoint) Descriptor() ([]byte, []int) {
	return file_data_points_proto_rawDescGZIP(), []int{5}
}

func (x *AggregateDatapoint) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AggregateDatapoint) GetAverage() float64 {
	if x != nil {
		return x.Average
	}
	return 0
}

func (x *AggregateDatapoint) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *AggregateDatapoint) GetMin() float64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *AggregateDatapoint) GetCount() float64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *AggregateDatapoint) GetSum() float64 {
	if x != nil {
		return x.Sum
	}
	return 0
}

func (x *AggregateDatapoint) GetInterpolation() float64 {
	if x != nil {
		return x.Interpolation
	}
	return 0
}

func (x *AggregateDatapoint) GetStepInterpolation() float64 {
	if x != nil {
		return x.StepInterpolation
	}
	return 0
}

func (x *AggregateDatapoint) GetContinuousVariance() float64 {
	if x != nil {
		return x.ContinuousVariance
	}
	return 0
}

func (x *AggregateDatapoint) GetDiscreteVariance() float64 {
	if x != nil {
		return x.DiscreteVariance
	}
	return 0
}

func (x *AggregateDatapoint) GetTotalVariation() float64 {
	if x != nil {
		return x.TotalVariation
	}
	return 0
}

func (x *AggregateDatapoint) GetCountGood() float64 {
	if x != nil {
		return x.CountGood
	}
	return 0
}

func (x *AggregateDatapoint) GetCountUncertain() float64 {
	if x != nil {
		return x.CountUncertain
	}
	return 0
}

func (x *AggregateDatapoint) GetCountBad() float64 {
	if x != nil {
		return x.CountBad
	}
	return 0
}

func (x *AggregateDatapoint) GetDurationGood() float64 {
	if x != nil {
		return x.DurationGood
	}
	return 0
}

func (x *AggregateDatapoint) GetDurationUncertain() float64 {
	if x != nil {
		return x.DurationUncertain
	}
	return 0
}

func (x *AggregateDatapoint) GetDurationBad() float64 {
	if x != nil {
		return x.DurationBad
	}
	return 0
}

func (x *AggregateDatapoint) GetMaxDatapoint() *NumericDatapoint {
	if x != nil {
		return x.MaxDatapoint
	}
	return nil
}

func (x *AggregateDatapoint) GetMinDatapoint() *NumericDatapoint {
	if x != nil {
		return x.MinDatapoint
	}
	return nil
}

type AggregateDatapoints struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Datapoints    []*AggregateDatapoint  `protobuf:"bytes,1,rep,name=datapoints,proto3" json:"datapoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregateDatapoints) Reset() {
	*x = AggregateDatapoints{}
	mi := &file_data_points_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregateDatapoints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregateDatapoints) ProtoMessage() {}

func (x *AggregateDatapoints) ProtoReflect() protoreflect.Message {
	mi := &file_data_points_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregateDatapoints.ProtoReflect.Descriptor instead.
func (*AggregateDatapoints) Descriptor() ([]byte, []int) {
	return file_data_points_proto_rawDescGZIP(), []int{6}
}

func (x *AggregateDatapoints) GetDatapoints() []*AggregateDatapoint {
	if x != nil {
		return x.Datapoints
	}
	return nil
}

type InstanceId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Space         string                 `protobuf:"bytes,1,opt,name=space,proto3" json:"space,omitempty"`
	ExternalId    string                 `protobuf:"bytes,2,opt,name=externalId,proto3" json:"externalId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceId) Reset() {
	*x = InstanceId{}
	mi := &file_data_points_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceId) ProtoMessage() {}

func (x *InstanceId) ProtoReflect() protoreflect.Message {
	mi := &file_data_points_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceId.ProtoReflect.Descriptor instead.
func (*InstanceId) Descriptor() ([]byte, []int) {
	return file_data_points_proto_rawDescGZIP(), []int{7}
}

func (x *InstanceId) GetSpace() string {
	if x != nil {
		return x.Space
	}
	return ""
}

func (x *InstanceId) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

var File_data_points_proto protoreflect.FileDescriptor

const file_data_points_proto_rawDesc = "" +
	"\n" +
	"\x11data_points.proto\x12\x1fcom.cognite.v1.timeseries.proto\"4\n" +
	"\x06Status\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\"\xa5\x01\n" +
	"\x10NumericDatapoint\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12?\n" +
	"\x06status\x18\x03 \x01(\v2'.com.cognite.v1.timeseries.proto.StatusR\x06status\x12\x1c\n" +
	"\tnullValue\x18\x04 \x01(\bR\tnullValue\"f\n" +
	"\x11NumericDatapoints\x12Q\n" +
	"\n" +
	"datapoints\x18\x01 \x03(\v21.com.cognite.v1.timeseries.proto.NumericDatapointR\n" +
	"datapoints\"\xa4\x01\n" +
	"\x0fStringDatapoint\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12?\n" +
	"\x06status\x18\x03 \x01(\v2'.com.cognite.v1.timeseries.proto.StatusR\x06status\x12\x1c\n" +
	"\tnullValue\x18\x04 \x01(\bR\tnullValue\"d\n" +
	"\x10StringDatapoints\x12P\n" +
	"\n" +
	"datapoints\x18\x01 \x03(\v20.com.cognite.v1.timeseries.proto.StringDatapointR\n" +
	"datapoints\"\xf4\x05\n" +
	"\x12AggregateDatapoint\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x18\n" +
	"\aaverage\x18\x02 \x01(\x01R\aaverage\x12\x10\n" +
	"\x03max\x18\x03 \x01(\x01R\x03max\x12\x10\n" +
	"\x03min\x18\x04 \x01(\x01R\x03min\x12\x14\n" +
	"\x05count\x18\x05 \x01(\x01R\x05count\x12\x10\n" +
	"\x03sum\x18\x06 \x01(\x01R\x03sum\x12$\n" +
	"\rinterpolation\x18\a \x01(\x01R\rinterpolation\x12,\n" +
	"\x11stepInterpolation\x18\b \x01(\x01R\x11stepInterpolation\x12.\n" +
	"\x12continuousVariance\x18\t \x01(\x01R\x12continuousVariance\x12*\n" +
	"\x10discreteVariance\x18\n" +
	" \x01(\x01R\x10discreteVariance\x12&\n" +
	"\x0etotalVariation\x18\v \x01(\x01R\x0etotalVariation\x12\x1c\n" +
	"\tcountGood\x18\f \x01(\x01R\tcountGood\x12&\n" +
	"\x0ecountUncertain\x18\r \x01(\x01R\x0ecountUncertain\x12\x1a\n" +
	"\bcountBad\x18\x0e \x01(\x01R\bcountBad\x12\"\n" +
	"\fdurationGood\x18\x0f \x01(\x01R\fdurationGood\x12,\n" +
	"\x11durationUncertain\x18\x10 \x01(\x01R\x11durationUncertain\x12 \n" +
	"\vdurationBad\x18\x11 \x01(\x01R\vdurationBad\x12U\n" +
	"\fmaxDatapoint\x18\x12 \x01(\v21.com.cognite.v1.timeseries.proto.NumericDatapointR\fmaxDatapoint\x12U\n" +
	"\fminDatapoint\x18\x13 \x01(\v21.com.cognite.v1.timeseries.proto.NumericDatapointR\fminDatapoint\"j\n" +
	"\x13AggregateDatapoints\x12S\n" +
	"\n" +
	"datapoints\x18\x01 \x03(\v23.com.cognite.v1.timeseries.proto.AggregateDatapointR\n" +
	"datapoints\"B\n" +
	"\n" +
	"InstanceId\x12\x14\n" +
	"\x05space\x18\x01 \x01(\tR\x05space\x12\x1e\n" +
	"\n" +
	"externalId\x18\x02 \x01(\tR\n" +
	"externalIdB5P\x01Z1github.com/evertoncolling/poc-requests-go/pkg/dtob\x06proto3"

var (
	file_data_points_proto_rawDescOnce sync.Once
	file_data_points_proto_rawDescData []byte
)

func file_data_points_proto_rawDescGZIP() []byte {
	file_data_points_proto_rawDescOnce.Do(func() {
		file_data_points_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_data_points_proto_rawDesc), len(file_data_points_proto_rawDesc)))
	})
	return file_data_points_proto_rawDescData
}

var file_data_points_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_data_points_proto_goTypes = []any{
	(*Status)(nil),              // 0: com.cognite.v1.timeseries.proto.Status
	(*NumericDatapoint)(nil),    // 1: com.cognite.v1.timeseries.proto.NumericDatapoint
	(*NumericDatapoints)(nil),   // 2: com.cognite.v1.timeseries.proto.NumericDatapoints
	(*StringDatapoint)(nil),     // 3: com.cognite.v1.timeseries.proto.StringDatapoint
	(*StringDatapoints)(nil),    // 4: com.cognite.v1.timeseries.proto.StringDatapoints
	(*AggregateDatapoint)(nil),  // 5: com.cognite.v1.timeseries.proto.AggregateDatapoint
	(*AggregateDatapoints)(nil), // 6: com.cognite.v1.timeseries.proto.AggregateDatapoints
	(*InstanceId)(nil),          // 7: com.cognite.v1.timeseries.proto.InstanceId
}
var file_data_points_proto_depIdxs = []int32{
	0, // 0: com.cognite.v1.timeseries.proto.NumericDatapoint.status:type_name -> com.cognite.v1.timeseries.proto.Status
	1, // 1: com.cognite.v1.timeseries.proto.NumericDatapoints.datapoints:type_name -> com.cognite.v1.timeseries.proto.NumericDatapoint
	0, // 2: com.cognite.v1.timeseries.proto.StringDatapoint.status:type_name -> com.cognite.v1.timeseries.proto.Status
	3, // 3: com.cognite.v1.timeseries.proto.StringDatapoints.datapoints:type_name -> com.cognite.v1.timeseries.proto.StringDatapoint
	1, // 4: com.cognite.v1.timeseries.proto.AggregateDatapoint.maxDatapoint:type_name -> com.cognite.v1.timeseries.proto.NumericDatapoint
	1, // 5: com.cognite.v1.timeseries.proto.AggregateDatapoint.minDatapoint:type_name -> com.cognite.v1.timeseries.proto.NumericDatapoint
	5, // 6: com.cognite.v1.timeseries.proto.AggregateDatapoints.datapoints:type_name -> com.cognite.v1.timeseries.proto.AggregateDatapoint
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_data_points_proto_init() }
func file_data_points_proto_init() {
	if File_data_points_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_data_points_proto_rawDesc), len(file_data_points_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_data_points_proto_goTypes,
		DependencyIndexes: file_data_points_proto_depIdxs,
		MessageInfos:      file_data_points_proto_msgTypes,
	}.Build()
	File_data_points_proto = out.File
	file_data_points_proto_goTypes = nil
	file_data_points_proto_depIdxs = nil
}
