name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build Release Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
        exclude:
          - goos: windows
            goarch: arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          output_name="poc-requests-go-${{ matrix.goos }}-${{ matrix.goarch }}"
          if [ "${{ matrix.goos }}" = "windows" ]; then
            output_name="${output_name}.exe"
          fi
          go build -ldflags="-s -w" -o "${output_name}" -v ./
          
          # Create archives
          if [ "${{ matrix.goos }}" = "windows" ]; then
            zip "${output_name%.exe}.zip" "${output_name}"
          else
            tar czf "${output_name}.tar.gz" "${output_name}"
          fi

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ matrix.goos }}-${{ matrix.goarch }}
          path: |
            *.tar.gz
            *.zip

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Display structure of downloaded files
        run: ls -la artifacts/*

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Move all binaries to current directory
          mv artifacts/*/* .
          
          # Create release with all binaries
          gh release create ${{ github.ref_name }} \
            --title "Release ${{ github.ref_name }}" \
            --notes "Release ${{ github.ref_name }} of poc-requests-go - A Go client library for Cognite Data Fusion (CDF) APIs

## Features
- **Time Series API** support:
  - List time series with filtering
  - Advanced filtering capabilities
  - Retrieve time series data points
  - Get latest data points
- **Units API** support:
  - Retrieve complete units catalog
- **Data Modeling API** support:
  - List data models
  - Search instances in data models
  - Execute GraphQL queries
- Azure credential provider for authentication
- Comprehensive test suite (unit and integration tests)
- CI/CD pipeline with GitHub Actions

## Installation

### Using go get
\`\`\`bash
go get github.com/evertoncolling/poc-requests-go
\`\`\`

### Using pre-built binaries
Download the appropriate binary for your platform from the assets below.

## Requirements
- Go 1.22 or higher (if building from source)
- Valid CDF credentials (client ID, secret, tenant ID)

## Documentation
See the [README](https://github.com/evertoncolling/poc-requests-go/blob/main/README.md) for detailed usage examples and API documentation." \
            *.tar.gz *.zip